[package]
name = "prime_sieve"
version = "0.1.0"
edition = "2021"

[lints.clippy]
enum_glob_use = "deny"
pedantic = "deny"
nursery = "deny"
unwrap_used = "deny"
expect_used = "deny"


[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
bisection = "0.1.0"